#include <stdlib.h>
#include <stdio.h>
#include "lime.c"
#include "cli.h"
#include "cli.c"
#include "utils.h"
#include "utils.c"
#include "cJSON.h"
#include "cJSON.c"
#include "daemon.h"
#include "daemon.c"
#include "objc.h"
#include "objc.m"